[versions]
org-junit-bom = "5.10.0"
org-assertj-core = "3.25.3"
com-h2database-mvstore = "2.2.224"
com-google-guava = "33.4.5-jre"
org-projectlombok = "1.18.42"
org-slf4j-api = "1.7.36"
net-thebugmc-gradle-sonatype-central-portal-publisher = "1.2.2"
org-awaitility = "4.3.0"
me-champeau-jmh = "0.7.3"

[libraries]
com-h2database-mvstore = { group = "com.h2database", name = "h2-mvstore", version.ref = "com-h2database-mvstore" }
org-projectlombok = { group = "org.projectlombok", name = "lombok", version.ref = "org-projectlombok" }
org-slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "org-slf4j-api" }
com-google-guava = { group = "com.google.guava", name = "guava", version.ref = "com-google-guava" }
org-junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "org-junit-bom" }
org-junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
org-junit-platform = { group = "org.junit.platform", name = "junit-platform-launcher" }
org-assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "org-assertj-core" }
org-awaitility = { group = "org.awaitility", name = "awaitility", version.ref = "org-awaitility" }

[plugins]
net-thebugmc-gradle-sonatype-central-portal-publisher = { id = "net.thebugmc.gradle.sonatype-central-portal-publisher", version.ref = "net-thebugmc-gradle-sonatype-central-portal-publisher" }
me-champeau-jmh = { id = "me.champeau.jmh", version.ref = "me-champeau-jmh" }
